# Generated by Django 4.0.3 on 2022-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAlertCode',
            fields=[
                ('alert_code', models.CharField(db_column='Alert_Code', max_length=10, primary_key=True, serialize=False)),
                ('alert_description', models.CharField(db_column='Alert_Description', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TblDeviceRawLength',
            fields=[
                ('device_type', models.CharField(db_column='Device_Type', max_length=50, primary_key=True, serialize=False)),
                ('raw_data_length', models.IntegerField(db_column='Raw_Data_Length')),
            ],
        ),
        migrations.CreateModel(
            name='TblGateway',
            fields=[
                ('gateway_id', models.CharField(db_column='Gateway_ID', max_length=50, primary_key=True, serialize=False)),
                ('gateway_location', models.CharField(db_column='Gateway_Location', max_length=50)),
                ('gateway_address', models.CharField(db_column='Gateway_Address', max_length=50)),
                ('gateway_mac', models.CharField(db_column='Gateway_Mac', max_length=50)),
                ('gateway_serial_no', models.CharField(db_column='Gateway_Serial_No', max_length=50)),
                ('gateway_topic', models.CharField(db_column='Gateway_Topic', max_length=50)),
                ('gateway_latitude', models.CharField(db_column='Gateway_Latitude', max_length=50)),
                ('gateway_longitude', models.CharField(db_column='Gateway_Longitude', max_length=50)),
                ('gateway_type', models.CharField(db_column='Gateway_Type', max_length=50)),
                ('device_tag', models.CharField(db_column='Device_Tag', max_length=50)),
                ('last_updated_time', models.DateTimeField()),
                ('gateway_status', models.CharField(db_column='Gateway_Status', max_length=50)),
            ],
        ),
    ]
