# Generated by Django 4.0.3 on 2022-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0002_tabledevice_alter_tblalertcode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBeacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('placement_location', models.CharField(max_length=100)),
                ('last_battery_date', models.DateField()),
                ('key', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Table Beacon',
                'verbose_name_plural': 'Table Beacon',
            },
        ),
    ]
