# Generated by Django 4.0.3 on 2022-06-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0004_tablebeacon_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableBeacon',
        ),
    ]
