# Generated by Django 4.0.3 on 2022-06-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0005_delete_tablebeacon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblalertcode',
            options={'verbose_name': 'Table Alert Code', 'verbose_name_plural': 'Table Alert Code'},
        ),
    ]
