# Generated by Django 4.0.3 on 2022-06-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0007_tabledevice_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_reading', models.CharField(max_length=50)),
                ('alert_date', models.DateField()),
                ('alert_time', models.TimeField()),
                ('sent_to_crest', models.IntegerField(default=0)),
                ('alert_datetime', models.DateTimeField()),
                ('alert_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluguard37.tblalertcode')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluguard37.tabledevice')),
            ],
            options={
                'verbose_name': 'Table Alert',
                'verbose_name_plural': 'Table Alert',
            },
        ),
    ]
