# Generated by Django 4.0.3 on 2022-07-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0010_tablealldevices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablealldevices',
            options={'ordering': ('-device_status', '-last_read_date', '-last_read_time'), 'verbose_name': 'Table Wearable', 'verbose_name_plural': 'Table Wearable'},
        ),
        migrations.AlterModelOptions(
            name='tabledevice',
            options={'ordering': ('-device_status', '-last_read_date', '-last_read_time'), 'verbose_name': 'Device', 'verbose_name_plural': 'Table Device'},
        ),
        migrations.AlterModelOptions(
            name='tablequarantine',
            options={'ordering': ('-device_status', '-last_read_date', '-last_read_time'), 'verbose_name': 'Table Quarantine', 'verbose_name_plural': 'Table Quarantine'},
        ),
        migrations.AlterField(
            model_name='tablealert',
            name='alert_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tablealert',
            name='alert_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tablealert',
            name='alert_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
