# Generated by Django 4.0.3 on 2022-07-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0013_scriptstatus_alter_tblgateway_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScriptStatus',
        ),
    ]
