# Generated by Django 4.0.3 on 2022-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0014_delete_scriptstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(default='OFFLINE', max_length=50)),
            ],
            options={
                'verbose_name': 'Script Status',
                'verbose_name_plural': 'Script Status',
            },
        ),
    ]
