# Generated by Django 4.0.6 on 2022-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0015_scriptstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgateway',
            name='device_tag',
            field=models.CharField(db_column='Device_Tag', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_address',
            field=models.CharField(db_column='Gateway_Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_id',
            field=models.CharField(db_column='Gateway_ID', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_latitude',
            field=models.CharField(db_column='Gateway_Latitude', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_location',
            field=models.CharField(db_column='Gateway_Location', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_longitude',
            field=models.CharField(db_column='Gateway_Longitude', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_mac',
            field=models.CharField(db_column='Gateway_Mac', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_serial_no',
            field=models.CharField(db_column='Gateway_Serial_No', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_status',
            field=models.CharField(db_column='Gateway_Status', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_topic',
            field=models.CharField(db_column='Gateway_Topic', max_length=200),
        ),
        migrations.AlterField(
            model_name='tblgateway',
            name='gateway_type',
            field=models.CharField(db_column='Gateway_Type', max_length=200),
        ),
    ]
