# Generated by Django 4.0.6 on 2022-07-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0016_alter_tblgateway_device_tag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblGateway',
        ),
    ]
