# Generated by Django 4.0.6 on 2022-07-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0017_delete_tblgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_location', models.CharField(db_column='Gateway_Location', max_length=200)),
                ('gateway_address', models.CharField(db_column='Gateway_Address', max_length=200)),
                ('gateway_mac', models.CharField(db_column='Gateway_Mac', max_length=200)),
                ('gateway_serial_no', models.CharField(db_column='Gateway_Serial_No', max_length=200)),
                ('gateway_topic', models.CharField(db_column='Gateway_Topic', max_length=200)),
                ('gateway_latitude', models.CharField(db_column='Gateway_Latitude', max_length=200)),
                ('gateway_longitude', models.CharField(db_column='Gateway_Longitude', max_length=200)),
                ('gateway_type', models.CharField(db_column='Gateway_Type', max_length=200)),
                ('device_tag', models.CharField(db_column='Device_Tag', max_length=200)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('gateway_status', models.CharField(db_column='Gateway_Status', max_length=200)),
            ],
            options={
                'verbose_name': 'Table Device Gateway',
                'verbose_name_plural': 'Table Device Gateway',
                'ordering': ('-gateway_status',),
            },
        ),
    ]
