# Generated by Django 4.0.3 on 2022-06-16 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_alter_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 15, 34, 36, 370486)),
        ),
        migrations.AddField(
            model_name='attendee',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 15, 34, 36, 370486)),
        ),
    ]
