# Generated by Django 4.0.3 on 2022-06-16 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_attendee_check_in_attendee_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='mac',
            field=models.CharField(default='FEFDD727C6F5', max_length=128),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 25, 5, 276645)),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 25, 5, 276645)),
        ),
    ]
