# Generated by Django 4.0.3 on 2022-06-16 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0016_alter_attendee_check_in_alter_attendee_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='check_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 16, 29, 14, 272273), null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='check_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 16, 29, 14, 273274), null=True),
        ),
    ]
