# Generated by Django 4.0.3 on 2022-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0017_alter_attendee_check_in_alter_attendee_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
