# Generated by Django 4.0.3 on 2022-06-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_alter_attendee_check_in_alter_attendee_check_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='mac',
            new_name='device_mac',
        ),
    ]
