# Generated by Django 4.0.3 on 2022-06-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_rename_mac_attendee_device_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='device_mac',
            field=models.CharField(max_length=128),
        ),
    ]
