# Generated by Django 4.0.3 on 2022-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_alter_attendee_device_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
