# Generated by Django 4.0.3 on 2022-06-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_attendee_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
