# Generated by Django 4.0.3 on 2022-06-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0023_attendee_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendees',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiapp.attendee'),
            preserve_default=False,
        ),
    ]
