# Generated by Django 4.0.3 on 2022-06-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0024_remove_attendance_attendees_attendance_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_name',
        ),
    ]
