# Generated by Django 4.0.3 on 2022-06-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0027_rename_attendee_ic_attendee_tag_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_tag', models.CharField(max_length=50)),
                ('device_mac', models.CharField(max_length=100)),
                ('device_status', models.CharField(max_length=20)),
                ('device_assignment', models.CharField(max_length=30)),
                ('device_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device_o2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device_bat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_read_date', models.DateField()),
                ('last_read_time', models.TimeField()),
            ],
        ),
    ]
