# Generated by Django 4.0.3 on 2022-06-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0029_alter_tabledevice_device_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_code', models.IntegerField(blank=True, null=True)),
                ('alert_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('alert_time', models.TimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.tabledevice')),
            ],
        ),
    ]
