# Generated by Django 4.0.3 on 2022-06-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0030_tablealert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablealert',
            options={'verbose_name': 'Alert', 'verbose_name_plural': 'Table Alert'},
        ),
        migrations.AlterModelOptions(
            name='tabledevice',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Table Device'},
        ),
        migrations.AddField(
            model_name='tabledevice',
            name='incorrect_data_flag',
            field=models.IntegerField(default=0),
        ),
    ]
