# Generated by Django 4.0.3 on 2022-06-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0031_alter_tablealert_options_alter_tabledevice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendee_name',
            field=models.CharField(default='Cinema', max_length=128),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.CharField(default='Cinema', max_length=128),
        ),
    ]
