# Generated by Django 4.0.3 on 2022-06-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0032_remove_attendance_attendee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Table Attendance', 'verbose_name_plural': 'Table Attendance'},
        ),
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'Table Attendee', 'verbose_name_plural': 'Table Attendee'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Table Event', 'verbose_name_plural': 'Table Event'},
        ),
    ]
