# Generated by Django 4.0.3 on 2022-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluguard37', '0003_tablebeacon'),
        ('apiapp', '0034_alter_attendee_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beacon',
            field=models.ManyToManyField(to='bluguard37.tablebeacon'),
        ),
    ]
