# Generated by Django 4.0.3 on 2022-06-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0035_event_beacon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='beacon',
        ),
    ]
