# Generated by Django 4.0.3 on 2022-07-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0043_alter_attendance_options_remove_attendee_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='check_out_time',
        ),
    ]
