# Generated by Django 4.0.3 on 2022-07-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0044_remove_attendee_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='active_event',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
