# Generated by Django 4.0.3 on 2022-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0045_attendee_active_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
