# Generated by Django 4.0.6 on 2022-07-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0047_alter_attendance_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['check_in_date', '-check_in_time'], 'verbose_name': 'Table Attendance', 'verbose_name_plural': 'Table Attendance'},
        ),
    ]
