# Generated by Django 4.0.6 on 2022-07-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0048_counter_alter_attendance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(blank=True, null=True, to='apiapp.attendee'),
        ),
    ]
